import type { Metadata } from "next";
import { Mona_Sans, Ultra } from "next/font/google";
import "./globals.css";

const arizonia = Ultra({
  variable: "--font-arizonia",
  subsets: ["latin"],
  weight: ["400"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable}  ${arizonia.className} ${arizonia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
